### ISSUE TITLE
directory option should not be text it should be folder list

### ISSUE THREAD

**Issue by zero-24** [Bakual/CustomFieldGallery#1]
directory option should not be text it should be folder list

**Comment by zero-24** [comment]
I'm currently on phone but iirc i have done that for the core field?

**Comment by Bakual** [comment]
You mean the one in the plugin itself?

I had to manually fix some things because my branch was a bit older and didn't had the latest code from staging. So some things were missing.

**Comment by zero-24** [comment]
Yes the change is missing here: https://github.com/Bakual/CustomFieldGallery/blob/master/gallery.xml in the params file it is done ;)
